name: Maven Container Demo
on:
  push:
    branches: [ master ]
jobs:
  maven-container-demo-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-jdk-8
      #env:
      #  NODE_ENV: development
      #ports:
      #  - 80
#       volumes:
#         - /opt/maven_dir/:/root/.m2/repository/
      # options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: /root/.m2/repository/
          key: ${{ runner.os }}-maven-v1-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-v1-maven-
      - name: Build with Maven
        run: mvn clean package
       # run: mvn clean package -Dmaven.repo.local=/root/.m2/repository/
       
       
